### ISSUE TITLE
Solve problems with existing output directory

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/neuralmonkey#61]
Its a pain when the data and the model are loading almost 10 minutes and then it crashes on existing output directory. The overwrite_output_dir option is nice but it does not work when you don't want to overwirite the output dir or if you are debugging and want to store the results.

Possible solutions include:
- check for the output directory before loading any data (this is my favorite)
- add an interactive version (that can be turned off) which asks you for a new dir name without need to re-run the experiment (more ugly)

**Comment by jlibovicky** [comment]
It's a bit tricky. If we would like to check whether the directory exists before creating any data structures, it  would have to be done during the first and second step of loading the configuration. Otherwise the configuration code will be interpreted and it includes creating all data structures written there. Also, this check would need to be active only while loading the configuration for training.

**Comment by jindrahelcl** [comment]
What if we make the `[main]` another object and move the `output` option to the global scope, together with an option with the name of the main section?

Then, we could first load the configuration from the global scope, and then load the main object. (Which will be given its class so it would be possible to use this config for different experiments.)

**Comment by jindrahelcl** [comment]
To be clear. This:

```
[main]
output=/some/folder
decoder=omg
```
would become this:

```
output=/some/folder
experiment=<dummy_main>

[dummy_main]
class=neuralmonkey.experiment
decoder=omg
```

**Comment by jindrahelcl** [comment]
For running the experiment, I can imagine this done in completely different directory from the training one. You can still have many decoding parameters, such as beam search size, so it makes sense to place different runs to different directories.

**Comment by tomasmcz** [comment]
@jlibovicky Again, that is why parsing the config (preferably with ConfigParser) needs to be a separate step. You need to be able to make decisions based on the configuration and run arbitrary code **before** any TF code is executed (and before anything else happens, eg. vocabulary creation). So no, _this is not tricky_ and you should not be thinking about bending the flawed config loader to create more unmaintainable mess, we should just fix the config loader.

**Comment by jlibovicky** [comment]
Again, parsing is a separate step. It is first parsed into a dictionary and then it resolved in the second step. Function `get_config_dicts` from `config_loader` does the job. Right now, it is called from a different function called `load_config_file` which also exectues the configuration. If you want to do anything in between the parsing and the execution (which may be a good idea), then you should just move the call of the first function from the second one. This is what I meant by "tricky" not bending anything.

If you are so keen on using ConfigParser, go ahead and refactor it. Although I am afraid it wouldn't make anything easier because most of the parsing is not parsing the INI format itself, which is super-easy, but parsing other constructs we added to the configuration (list, references, python classes and functions).

**Comment by tomasmcz** [comment]
I checked before writing my previous comment and it is not a separate step in the current API. The `Configuration` class only has one method (`load_file`), that has to be split into two (second one being something like `execute`). The same goes for `config_loader`, where `load_config_file` needs to be split into two functions. 

I, as the user of `neuralmonkey.config` module, am not able to read the configuration, do something and then execute the configuration, without completely ignoring the `Configuration` class and copying and modifying the entire `load_config_file`, which is clearly an incorrect way to go.

What you're saying is basically "of course it's a separate step if you refactor half of one module and completely ignore the other one".

You could say that the implementation is ready to be easily refactored into two steps, but that's not the important thing. The semantics of the API is the thing we should be concerned (and talking) about and the implementation should be adapted to that. When you do it the other way around (adapting the API to the implementation and ignoring its semantics) you end up with "we can't use higher order function, because we generate configuration from existing objects" (clear violation of principle of encapsulation, btw.).

As for ConfigParser, I'll look into that later, but it's not really important.

**Comment by tomasmcz** [comment]
To summarize the problem: it might be happening separately now, but since there is no way to call it separately, how am I supposed to know? It might as well be interleaved, for all care, because I as a user of the module am not able to distinguish that.

**Comment by tomasmcz** [comment]
And to summarize the solution: there is nothing *tricky* about it, fixing the `config` subpackage to enable checking things between parsing and execution is the correct way to go.

**Comment by jlibovicky** [comment]
OK, tricky maybe was not the right word, but what I mean from the beginning is: do this simple refactor if you want check the configuration before execution. And you are supposed to know how it is implemented because we first agreed how the configuration will look like #17, then I implemented it and made a pull request you agreed with #43.

**Comment by tomasmcz** [comment]
You're still missing the main point (which is that *implementation is irrelevant*) but anyway:
In #17 you didn't specify which of the proposed changes you will actually implement and I can't find any mentions of separation of parsing and execution there (and as far as I am concerned, it is still not implemented, because there is no way to actually use it). I merged #43, because it got rid of the crazy config generation – again, nothing to do with the separation of parsing.

Whatever you meant (you know my views on "meaning something"), your initial comment seemed to indicate that you are against that and lead to proposals of unnecessary complications in the specification of the configuration.  So you should apparently brush up on your Grice's maxims, before writing something like "It's a bit tricky."

Do you want to continue this superfluous discussion, or shall we just agree to refactor the config?

**Comment by jlibovicky** [comment]
Sure, do the refactor.

**Comment by jindrahelcl** [comment]
Ty káro to je zase smršť.. Jestli mezi hlavní argumenty pro používání angličtiny je, aby to každej po letech mohl dohledat, tak doufám, že až budu chtít v důchodu zavzpomínat a trochu se zasmát, že ještě budu tý dnešní angličtině rozumět. Pokud ale maj mít tyhle diskuse skutečnou hodnotu, vyvaroval bych se kratších komentářů založenejch na konkrétní osobě nebo vztahu (e.g. 'you know my views...'), čtenář si to pak bez potřebnýho kontextu nemůže tak vychutnat.

Co se týče samotný diskuse, rád bych pokračoval od místa, než sem @tomasmcz zanes první omgy jak vyšitý z profilový informace na líbímseti pro programátory a jejich hejtry. Viz muj post "For running the experiment ..."

**Comment by tomasmcz** [comment]
@jindrahelcl: Nevím co jsem kam zanesl, mám dojem že až na odpověď na to, že jsem "supposed to know" něco, co podle mne ani není pravda, jsem psal všechno k tématu, tj. k rozdělení parsování a exekuce a k tomu, že je třeba se bavit o tom jak *má vypadat API*, ne jak shodou okolností *vypadá implementace*. Drobnými osobními poznámkami (typu "you know my views") podle mne diskuse žádnou zásadní škodu neutrpí a nevadí mi ani debatovat o tom, jakým způsobem máme či nemáme vést debatu, nicméně *ad hominem* příspěvek vyzívající k návratu k technické diskusi mi připadá poněkud vnitřně nekonzistentní.

**Comment by tomasmcz** [comment]
Ad "For running the experiment ...": If we want to have multiple experiments (or runs) in one ini file, we might do that, but that is a separate issue and you would still need to check whether the directories exist, so we need to fix the `config` anyway.

**Comment by tomasmcz** [comment]
If no-one gets to it sooner, I will fix the `config` API as preliminary work on #56, but it has fairly low priority right now (see the pre-MTM milestone list – it is sorted).

**Comment by jindrahelcl** [comment]
I have already give it some thought so before you start on it, check with me first so we don't do the same thing twice.

**Comment by jindrahelcl** [comment]
@tomasmcz já bych byl jen rád, kdyby mi někdo odpověděl na moje otázky, který jsem v týhle issue položil - který se netýkaly implementace, ale rozhraní - místo toho, aby se tu řešilo znova všechno odznova. Na to můžeš vytvořit jinou issue. Odpověď na "For running the experiment" nepovažuju za odpověď protože odpovídá na něco jinýho. Řikal jsem, že si dovedu představit, že bude jeden experiment v jedný složce trénovanej a každý spuštění vytvoří novou složku, ne že bude jeden konfigurák na víc experimentů. Tím jsem reagoval na @jlibovicky's komentář 

> Also, this check would need to be active only while loading the configuration for training.

Chci se bavit o tom, jak ten konfigurák má vypadat. Ale pokud někdo mluví o implementaci a o problémech, který se při ní musely řešit, tak je to cenná informace pro design a je špatný řikat, že se komentáře o implementaci nepatří.

**Comment by tomasmcz** [comment]
@jindrahelcl tady se motá strašně moc věcí dohromady a asi by bylo vhodné to nějak rozdělit. Tenhle issue byl o tom, že se dlouho loaduje spousta věcí a pak to spadne, protože složka existuje. To se vyřeší tím, že se rozdělí čtení a provádění konfigurace a kontrola existence složky se dá do trénovacího skripu mezi to. Žádné změny formátu konfigurace s tím nemají co dělat. Jestli má každý run vytvářet novou složku to nevím, ale nemělo by se to řešit tady. (A psal bych to pod `[runner]`, nebo možná do nějakého `data.ini`, který si ale vlastně nejsem jistý proč máme, odtud moje zmatení stran experimentů/souborů.).

Takže tady jsme se (doufám) dohodli na řešení problému, to by se mělo implementovat a tenhle issue zavřít. Jestli Tě při tom napadly nějaké další věci, které by se měli řešit, tak je prosím jasně formuluj (nejlépe v novém issue), jinak je v tom hrozný zmatek.

Pokud se chceš bavit o tom, jak má vypadat konfigurák, bavme se o tom při specifikaci konfiguráku. S poslední větou nesouhlasím. Podle mne je potřeba se domluvit *jak má vypadat konfigurák* a to je něco, co nemůže být určováno tím *jak vypadá současná implementace*, která vznikala naprosto *ad hoc*. Nechci tvrdit, že diskuse o implementaci je obecně úplně irelevantní, ale že současná implementace (nota bene pokud je pro uživatele nepřístupná, protože jí nemůže zavolat, aniž by se zároveň děla spousta jiných věcí) není argumentem pro podobu API a konfiguráků.

**Comment by jindrahelcl** [comment]
Netvrdim, že to má být určováno tím, jak současná implementace vypadá, jenomže je chyba ignorovat veškerý poznatky, na který se při vyrábění současný implementace narazilo.

**Comment by tomasmcz** [comment]
A já zas tvrdím, že žádné relevantní poznatky, které by bylo možné ignorovat, neexistujou, protože současná implementace (respektive všechny její aspekty zmiňované v diskusi výše) vznikala zcela *ad hoc*, bez procesu návrhu, při kterém by mohly relevantní poznatky vznikat. Relevantní argument by musel znít "máme návrh a z vlastností předchozí implementace o něm něco víme", ne "máme implementaci a proto...".

**Comment by jlibovicky** [comment]
Uf.
